### ISSUE TITLE
Unnecessary integer casting/ceiling

### ISSUE THREAD

**Issue by kykungz** [OOP2018/guessing-game-pknn1#4]
Since `upBound` `lowBound` and `2` are `int`, `(upBound - lowBound) / 2` results in `int` value.
`int` value is ~ceiled~ discarding fractional part by default, so you don't need to have `Math.ceil` anymore.
https://github.com/OOP2018/guessing-game-pknn1/blob/d6e9712fb947ec49b23919b18be29c2b7371f44e/src/GameSolver.java#L45

**Comment by ghost** [comment]
`int` value isn't ceiled by default. 
Take `int a = 3/2;` or `int a = (int)(3.00/2.00);` for the example. According to the Oracle Documentation, `int` variable will only **Discard the fractional part** of the value. So, 3 / 2 = 1.5 and `int` will discard the .5 part and the answer will be 1.

**Comment by kykungz** [comment]
Right, sorry for misusing the word, fixed. 👍
